# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

from qna_generation_agent.infrastructure.grpc.stubs.assessorflow.submission.v1 import (
    submission_pb2 as assessorflow_dot_submission_dot_v1_dot_submission__pb2,
)

GRPC_GENERATED_VERSION = "1.80.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in assessorflow/submission/v1/submission_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class SubmissionServiceStub(object):
    """Assessment Submission Service — internal gRPC API (api_contract.md Section 2)
    Central record keeper: owns assessment config, materials, questions, submissions, evaluations, reports.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAssessmentConfig = channel.unary_unary(
            "/assessorflow.submission.v1.SubmissionService/GetAssessmentConfig",
            request_serializer=assessorflow_dot_submission_dot_v1_dot_submission__pb2.GetAssessmentConfigRequest.SerializeToString,
            response_deserializer=assessorflow_dot_submission_dot_v1_dot_submission__pb2.GetAssessmentConfigResponse.FromString,
            _registered_method=True,
        )
        self.GetMaterials = channel.unary_unary(
            "/assessorflow.submission.v1.SubmissionService/GetMaterials",
            request_serializer=assessorflow_dot_submission_dot_v1_dot_submission__pb2.GetMaterialsRequest.SerializeToString,
            response_deserializer=assessorflow_dot_submission_dot_v1_dot_submission__pb2.GetMaterialsResponse.FromString,
            _registered_method=True,
        )
        self.CreateQuestionSet = channel.unary_unary(
            "/assessorflow.submission.v1.SubmissionService/CreateQuestionSet",
            request_serializer=assessorflow_dot_submission_dot_v1_dot_submission__pb2.CreateQuestionSetRequest.SerializeToString,
            response_deserializer=assessorflow_dot_submission_dot_v1_dot_submission__pb2.CreateQuestionSetResponse.FromString,
            _registered_method=True,
        )
        self.WriteGeneratedQuestions = channel.unary_unary(
            "/assessorflow.submission.v1.SubmissionService/WriteGeneratedQuestions",
            request_serializer=assessorflow_dot_submission_dot_v1_dot_submission__pb2.WriteGeneratedQuestionsRequest.SerializeToString,
            response_deserializer=assessorflow_dot_submission_dot_v1_dot_submission__pb2.WriteGeneratedQuestionsResponse.FromString,
            _registered_method=True,
        )
        self.GetGeneratedQuestionsWithAnswers = channel.unary_unary(
            "/assessorflow.submission.v1.SubmissionService/GetGeneratedQuestionsWithAnswers",
            request_serializer=assessorflow_dot_submission_dot_v1_dot_submission__pb2.GetGeneratedQuestionsRequest_.SerializeToString,
            response_deserializer=assessorflow_dot_submission_dot_v1_dot_submission__pb2.GetGeneratedQuestionsResponse.FromString,
            _registered_method=True,
        )
        self.IncrementQuestionSetIteration = channel.unary_unary(
            "/assessorflow.submission.v1.SubmissionService/IncrementQuestionSetIteration",
            request_serializer=assessorflow_dot_submission_dot_v1_dot_submission__pb2.IncrementIterationRequest.SerializeToString,
            response_deserializer=assessorflow_dot_submission_dot_v1_dot_submission__pb2.IncrementIterationResponse.FromString,
            _registered_method=True,
        )
        self.GetApprovedQuestionsWithAnswers = channel.unary_unary(
            "/assessorflow.submission.v1.SubmissionService/GetApprovedQuestionsWithAnswers",
            request_serializer=assessorflow_dot_submission_dot_v1_dot_submission__pb2.GetApprovedQuestionsRequest.SerializeToString,
            response_deserializer=assessorflow_dot_submission_dot_v1_dot_submission__pb2.GetApprovedQuestionsResponse.FromString,
            _registered_method=True,
        )
        self.CreateEvaluation = channel.unary_unary(
            "/assessorflow.submission.v1.SubmissionService/CreateEvaluation",
            request_serializer=assessorflow_dot_submission_dot_v1_dot_submission__pb2.CreateEvaluationRequest.SerializeToString,
            response_deserializer=assessorflow_dot_submission_dot_v1_dot_submission__pb2.CreateEvaluationResponse.FromString,
            _registered_method=True,
        )
        self.CreateGroupEvaluation = channel.unary_unary(
            "/assessorflow.submission.v1.SubmissionService/CreateGroupEvaluation",
            request_serializer=assessorflow_dot_submission_dot_v1_dot_submission__pb2.CreateGroupEvaluationRequest.SerializeToString,
            response_deserializer=assessorflow_dot_submission_dot_v1_dot_submission__pb2.CreateGroupEvaluationResponse.FromString,
            _registered_method=True,
        )
        self.GetEvaluation = channel.unary_unary(
            "/assessorflow.submission.v1.SubmissionService/GetEvaluation",
            request_serializer=assessorflow_dot_submission_dot_v1_dot_submission__pb2.GetEvaluationRequest.SerializeToString,
            response_deserializer=assessorflow_dot_submission_dot_v1_dot_submission__pb2.GetEvaluationResponse.FromString,
            _registered_method=True,
        )
        self.CreateReport = channel.unary_unary(
            "/assessorflow.submission.v1.SubmissionService/CreateReport",
            request_serializer=assessorflow_dot_submission_dot_v1_dot_submission__pb2.CreateReportRequest.SerializeToString,
            response_deserializer=assessorflow_dot_submission_dot_v1_dot_submission__pb2.CreateReportResponse.FromString,
            _registered_method=True,
        )
        self.UploadWebResearchMaterials = channel.unary_unary(
            "/assessorflow.submission.v1.SubmissionService/UploadWebResearchMaterials",
            request_serializer=assessorflow_dot_submission_dot_v1_dot_submission__pb2.UploadWebResearchRequest.SerializeToString,
            response_deserializer=assessorflow_dot_submission_dot_v1_dot_submission__pb2.UploadWebResearchResponse.FromString,
            _registered_method=True,
        )
        self.StartWorkflow = channel.unary_unary(
            "/assessorflow.submission.v1.SubmissionService/StartWorkflow",
            request_serializer=assessorflow_dot_submission_dot_v1_dot_submission__pb2.StartWorkflowRequest.SerializeToString,
            response_deserializer=assessorflow_dot_submission_dot_v1_dot_submission__pb2.StartWorkflowResponse.FromString,
            _registered_method=True,
        )


class SubmissionServiceServicer(object):
    """Assessment Submission Service — internal gRPC API (api_contract.md Section 2)
    Central record keeper: owns assessment config, materials, questions, submissions, evaluations, reports.
    """

    def GetAssessmentConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetMaterials(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CreateQuestionSet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def WriteGeneratedQuestions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetGeneratedQuestionsWithAnswers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def IncrementQuestionSetIteration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetApprovedQuestionsWithAnswers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CreateEvaluation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CreateGroupEvaluation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetEvaluation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CreateReport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def UploadWebResearchMaterials(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def StartWorkflow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_SubmissionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetAssessmentConfig": grpc.unary_unary_rpc_method_handler(
            servicer.GetAssessmentConfig,
            request_deserializer=assessorflow_dot_submission_dot_v1_dot_submission__pb2.GetAssessmentConfigRequest.FromString,
            response_serializer=assessorflow_dot_submission_dot_v1_dot_submission__pb2.GetAssessmentConfigResponse.SerializeToString,
        ),
        "GetMaterials": grpc.unary_unary_rpc_method_handler(
            servicer.GetMaterials,
            request_deserializer=assessorflow_dot_submission_dot_v1_dot_submission__pb2.GetMaterialsRequest.FromString,
            response_serializer=assessorflow_dot_submission_dot_v1_dot_submission__pb2.GetMaterialsResponse.SerializeToString,
        ),
        "CreateQuestionSet": grpc.unary_unary_rpc_method_handler(
            servicer.CreateQuestionSet,
            request_deserializer=assessorflow_dot_submission_dot_v1_dot_submission__pb2.CreateQuestionSetRequest.FromString,
            response_serializer=assessorflow_dot_submission_dot_v1_dot_submission__pb2.CreateQuestionSetResponse.SerializeToString,
        ),
        "WriteGeneratedQuestions": grpc.unary_unary_rpc_method_handler(
            servicer.WriteGeneratedQuestions,
            request_deserializer=assessorflow_dot_submission_dot_v1_dot_submission__pb2.WriteGeneratedQuestionsRequest.FromString,
            response_serializer=assessorflow_dot_submission_dot_v1_dot_submission__pb2.WriteGeneratedQuestionsResponse.SerializeToString,
        ),
        "GetGeneratedQuestionsWithAnswers": grpc.unary_unary_rpc_method_handler(
            servicer.GetGeneratedQuestionsWithAnswers,
            request_deserializer=assessorflow_dot_submission_dot_v1_dot_submission__pb2.GetGeneratedQuestionsRequest_.FromString,
            response_serializer=assessorflow_dot_submission_dot_v1_dot_submission__pb2.GetGeneratedQuestionsResponse.SerializeToString,
        ),
        "IncrementQuestionSetIteration": grpc.unary_unary_rpc_method_handler(
            servicer.IncrementQuestionSetIteration,
            request_deserializer=assessorflow_dot_submission_dot_v1_dot_submission__pb2.IncrementIterationRequest.FromString,
            response_serializer=assessorflow_dot_submission_dot_v1_dot_submission__pb2.IncrementIterationResponse.SerializeToString,
        ),
        "GetApprovedQuestionsWithAnswers": grpc.unary_unary_rpc_method_handler(
            servicer.GetApprovedQuestionsWithAnswers,
            request_deserializer=assessorflow_dot_submission_dot_v1_dot_submission__pb2.GetApprovedQuestionsRequest.FromString,
            response_serializer=assessorflow_dot_submission_dot_v1_dot_submission__pb2.GetApprovedQuestionsResponse.SerializeToString,
        ),
        "CreateEvaluation": grpc.unary_unary_rpc_method_handler(
            servicer.CreateEvaluation,
            request_deserializer=assessorflow_dot_submission_dot_v1_dot_submission__pb2.CreateEvaluationRequest.FromString,
            response_serializer=assessorflow_dot_submission_dot_v1_dot_submission__pb2.CreateEvaluationResponse.SerializeToString,
        ),
        "CreateGroupEvaluation": grpc.unary_unary_rpc_method_handler(
            servicer.CreateGroupEvaluation,
            request_deserializer=assessorflow_dot_submission_dot_v1_dot_submission__pb2.CreateGroupEvaluationRequest.FromString,
            response_serializer=assessorflow_dot_submission_dot_v1_dot_submission__pb2.CreateGroupEvaluationResponse.SerializeToString,
        ),
        "GetEvaluation": grpc.unary_unary_rpc_method_handler(
            servicer.GetEvaluation,
            request_deserializer=assessorflow_dot_submission_dot_v1_dot_submission__pb2.GetEvaluationRequest.FromString,
            response_serializer=assessorflow_dot_submission_dot_v1_dot_submission__pb2.GetEvaluationResponse.SerializeToString,
        ),
        "CreateReport": grpc.unary_unary_rpc_method_handler(
            servicer.CreateReport,
            request_deserializer=assessorflow_dot_submission_dot_v1_dot_submission__pb2.CreateReportRequest.FromString,
            response_serializer=assessorflow_dot_submission_dot_v1_dot_submission__pb2.CreateReportResponse.SerializeToString,
        ),
        "UploadWebResearchMaterials": grpc.unary_unary_rpc_method_handler(
            servicer.UploadWebResearchMaterials,
            request_deserializer=assessorflow_dot_submission_dot_v1_dot_submission__pb2.UploadWebResearchRequest.FromString,
            response_serializer=assessorflow_dot_submission_dot_v1_dot_submission__pb2.UploadWebResearchResponse.SerializeToString,
        ),
        "StartWorkflow": grpc.unary_unary_rpc_method_handler(
            servicer.StartWorkflow,
            request_deserializer=assessorflow_dot_submission_dot_v1_dot_submission__pb2.StartWorkflowRequest.FromString,
            response_serializer=assessorflow_dot_submission_dot_v1_dot_submission__pb2.StartWorkflowResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "assessorflow.submission.v1.SubmissionService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "assessorflow.submission.v1.SubmissionService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class SubmissionService(object):
    """Assessment Submission Service — internal gRPC API (api_contract.md Section 2)
    Central record keeper: owns assessment config, materials, questions, submissions, evaluations, reports.
    """

    @staticmethod
    def GetAssessmentConfig(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/assessorflow.submission.v1.SubmissionService/GetAssessmentConfig",
            assessorflow_dot_submission_dot_v1_dot_submission__pb2.GetAssessmentConfigRequest.SerializeToString,
            assessorflow_dot_submission_dot_v1_dot_submission__pb2.GetAssessmentConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetMaterials(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/assessorflow.submission.v1.SubmissionService/GetMaterials",
            assessorflow_dot_submission_dot_v1_dot_submission__pb2.GetMaterialsRequest.SerializeToString,
            assessorflow_dot_submission_dot_v1_dot_submission__pb2.GetMaterialsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CreateQuestionSet(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/assessorflow.submission.v1.SubmissionService/CreateQuestionSet",
            assessorflow_dot_submission_dot_v1_dot_submission__pb2.CreateQuestionSetRequest.SerializeToString,
            assessorflow_dot_submission_dot_v1_dot_submission__pb2.CreateQuestionSetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def WriteGeneratedQuestions(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/assessorflow.submission.v1.SubmissionService/WriteGeneratedQuestions",
            assessorflow_dot_submission_dot_v1_dot_submission__pb2.WriteGeneratedQuestionsRequest.SerializeToString,
            assessorflow_dot_submission_dot_v1_dot_submission__pb2.WriteGeneratedQuestionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetGeneratedQuestionsWithAnswers(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/assessorflow.submission.v1.SubmissionService/GetGeneratedQuestionsWithAnswers",
            assessorflow_dot_submission_dot_v1_dot_submission__pb2.GetGeneratedQuestionsRequest_.SerializeToString,
            assessorflow_dot_submission_dot_v1_dot_submission__pb2.GetGeneratedQuestionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def IncrementQuestionSetIteration(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/assessorflow.submission.v1.SubmissionService/IncrementQuestionSetIteration",
            assessorflow_dot_submission_dot_v1_dot_submission__pb2.IncrementIterationRequest.SerializeToString,
            assessorflow_dot_submission_dot_v1_dot_submission__pb2.IncrementIterationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetApprovedQuestionsWithAnswers(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/assessorflow.submission.v1.SubmissionService/GetApprovedQuestionsWithAnswers",
            assessorflow_dot_submission_dot_v1_dot_submission__pb2.GetApprovedQuestionsRequest.SerializeToString,
            assessorflow_dot_submission_dot_v1_dot_submission__pb2.GetApprovedQuestionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CreateEvaluation(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/assessorflow.submission.v1.SubmissionService/CreateEvaluation",
            assessorflow_dot_submission_dot_v1_dot_submission__pb2.CreateEvaluationRequest.SerializeToString,
            assessorflow_dot_submission_dot_v1_dot_submission__pb2.CreateEvaluationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CreateGroupEvaluation(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/assessorflow.submission.v1.SubmissionService/CreateGroupEvaluation",
            assessorflow_dot_submission_dot_v1_dot_submission__pb2.CreateGroupEvaluationRequest.SerializeToString,
            assessorflow_dot_submission_dot_v1_dot_submission__pb2.CreateGroupEvaluationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetEvaluation(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/assessorflow.submission.v1.SubmissionService/GetEvaluation",
            assessorflow_dot_submission_dot_v1_dot_submission__pb2.GetEvaluationRequest.SerializeToString,
            assessorflow_dot_submission_dot_v1_dot_submission__pb2.GetEvaluationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CreateReport(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/assessorflow.submission.v1.SubmissionService/CreateReport",
            assessorflow_dot_submission_dot_v1_dot_submission__pb2.CreateReportRequest.SerializeToString,
            assessorflow_dot_submission_dot_v1_dot_submission__pb2.CreateReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def UploadWebResearchMaterials(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/assessorflow.submission.v1.SubmissionService/UploadWebResearchMaterials",
            assessorflow_dot_submission_dot_v1_dot_submission__pb2.UploadWebResearchRequest.SerializeToString,
            assessorflow_dot_submission_dot_v1_dot_submission__pb2.UploadWebResearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def StartWorkflow(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/assessorflow.submission.v1.SubmissionService/StartWorkflow",
            assessorflow_dot_submission_dot_v1_dot_submission__pb2.StartWorkflowRequest.SerializeToString,
            assessorflow_dot_submission_dot_v1_dot_submission__pb2.StartWorkflowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
