# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

from qna_generation_agent.infrastructure.grpc.stubs.assessorflow.knowledge.v1 import (
    knowledge_pb2 as assessorflow_dot_knowledge_dot_v1_dot_knowledge__pb2,
)

GRPC_GENERATED_VERSION = "1.80.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in assessorflow/knowledge/v1/knowledge_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class KnowledgeServiceStub(object):
    """Knowledge Service — internal gRPC API (api_contract.md Section 3)
    RAG pipeline: chunking, embedding, similarity search across 3 Knowledge Bases.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTopics = channel.unary_unary(
            "/assessorflow.knowledge.v1.KnowledgeService/GetTopics",
            request_serializer=assessorflow_dot_knowledge_dot_v1_dot_knowledge__pb2.GetTopicsRequest.SerializeToString,
            response_deserializer=assessorflow_dot_knowledge_dot_v1_dot_knowledge__pb2.GetTopicsResponse.FromString,
            _registered_method=True,
        )
        self.SimilaritySearch = channel.unary_unary(
            "/assessorflow.knowledge.v1.KnowledgeService/SimilaritySearch",
            request_serializer=assessorflow_dot_knowledge_dot_v1_dot_knowledge__pb2.SimilaritySearchRequest.SerializeToString,
            response_deserializer=assessorflow_dot_knowledge_dot_v1_dot_knowledge__pb2.SimilaritySearchResponse.FromString,
            _registered_method=True,
        )
        self.GetChunksByIds = channel.unary_unary(
            "/assessorflow.knowledge.v1.KnowledgeService/GetChunksByIds",
            request_serializer=assessorflow_dot_knowledge_dot_v1_dot_knowledge__pb2.GetChunksByIdsRequest.SerializeToString,
            response_deserializer=assessorflow_dot_knowledge_dot_v1_dot_knowledge__pb2.GetChunksByIdsResponse.FromString,
            _registered_method=True,
        )


class KnowledgeServiceServicer(object):
    """Knowledge Service — internal gRPC API (api_contract.md Section 3)
    RAG pipeline: chunking, embedding, similarity search across 3 Knowledge Bases.
    """

    def GetTopics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SimilaritySearch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetChunksByIds(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_KnowledgeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetTopics": grpc.unary_unary_rpc_method_handler(
            servicer.GetTopics,
            request_deserializer=assessorflow_dot_knowledge_dot_v1_dot_knowledge__pb2.GetTopicsRequest.FromString,
            response_serializer=assessorflow_dot_knowledge_dot_v1_dot_knowledge__pb2.GetTopicsResponse.SerializeToString,
        ),
        "SimilaritySearch": grpc.unary_unary_rpc_method_handler(
            servicer.SimilaritySearch,
            request_deserializer=assessorflow_dot_knowledge_dot_v1_dot_knowledge__pb2.SimilaritySearchRequest.FromString,
            response_serializer=assessorflow_dot_knowledge_dot_v1_dot_knowledge__pb2.SimilaritySearchResponse.SerializeToString,
        ),
        "GetChunksByIds": grpc.unary_unary_rpc_method_handler(
            servicer.GetChunksByIds,
            request_deserializer=assessorflow_dot_knowledge_dot_v1_dot_knowledge__pb2.GetChunksByIdsRequest.FromString,
            response_serializer=assessorflow_dot_knowledge_dot_v1_dot_knowledge__pb2.GetChunksByIdsResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "assessorflow.knowledge.v1.KnowledgeService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "assessorflow.knowledge.v1.KnowledgeService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class KnowledgeService(object):
    """Knowledge Service — internal gRPC API (api_contract.md Section 3)
    RAG pipeline: chunking, embedding, similarity search across 3 Knowledge Bases.
    """

    @staticmethod
    def GetTopics(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/assessorflow.knowledge.v1.KnowledgeService/GetTopics",
            assessorflow_dot_knowledge_dot_v1_dot_knowledge__pb2.GetTopicsRequest.SerializeToString,
            assessorflow_dot_knowledge_dot_v1_dot_knowledge__pb2.GetTopicsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def SimilaritySearch(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/assessorflow.knowledge.v1.KnowledgeService/SimilaritySearch",
            assessorflow_dot_knowledge_dot_v1_dot_knowledge__pb2.SimilaritySearchRequest.SerializeToString,
            assessorflow_dot_knowledge_dot_v1_dot_knowledge__pb2.SimilaritySearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetChunksByIds(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/assessorflow.knowledge.v1.KnowledgeService/GetChunksByIds",
            assessorflow_dot_knowledge_dot_v1_dot_knowledge__pb2.GetChunksByIdsRequest.SerializeToString,
            assessorflow_dot_knowledge_dot_v1_dot_knowledge__pb2.GetChunksByIdsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
