# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: assessorflow/knowledge/v1/knowledge.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'assessorflow/knowledge/v1/knowledge.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)assessorflow/knowledge/v1/knowledge.proto\x12\x19\x61ssessorflow.knowledge.v1\"\xd6\x01\n\x05\x43hunk\x12\x10\n\x08\x63hunk_id\x18\x01 \x01(\t\x12\x13\n\x0bworkflow_id\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x13\n\x0bsource_type\x18\x04 \x01(\t\x12@\n\x08metadata\x18\x05 \x03(\x0b\x32..assessorflow.knowledge.v1.Chunk.MetadataEntry\x12\r\n\x05score\x18\x06 \x01(\x01\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\\\n\x05Topic\x12\x10\n\x08topic_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x33\n\tsubtopics\x18\x03 \x03(\x0b\x32 .assessorflow.knowledge.v1.Topic\"\'\n\x10GetTopicsRequest\x12\x13\n\x0bworkflow_id\x18\x01 \x01(\t\"Z\n\x11GetTopicsResponse\x12\x13\n\x0bworkflow_id\x18\x01 \x01(\t\x12\x30\n\x06topics\x18\x02 \x03(\x0b\x32 .assessorflow.knowledge.v1.Topic\"t\n\x17SimilaritySearchRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x13\n\x0bworkflow_id\x18\x02 \x01(\t\x12\x0f\n\x07kb_type\x18\x03 \x01(\t\x12\r\n\x05top_k\x18\x04 \x01(\x05\x12\x15\n\rassessment_id\x18\x05 \x01(\t\"a\n\x18SimilaritySearchResponse\x12\x13\n\x0bworkflow_id\x18\x01 \x01(\t\x12\x30\n\x06\x63hunks\x18\x02 \x03(\x0b\x32 .assessorflow.knowledge.v1.Chunk\"*\n\x15GetChunksByIdsRequest\x12\x11\n\tchunk_ids\x18\x01 \x03(\t\"J\n\x16GetChunksByIdsResponse\x12\x30\n\x06\x63hunks\x18\x01 \x03(\x0b\x32 .assessorflow.knowledge.v1.Chunk2\xee\x02\n\x10KnowledgeService\x12\x66\n\tGetTopics\x12+.assessorflow.knowledge.v1.GetTopicsRequest\x1a,.assessorflow.knowledge.v1.GetTopicsResponse\x12{\n\x10SimilaritySearch\x12\x32.assessorflow.knowledge.v1.SimilaritySearchRequest\x1a\x33.assessorflow.knowledge.v1.SimilaritySearchResponse\x12u\n\x0eGetChunksByIds\x12\x30.assessorflow.knowledge.v1.GetChunksByIdsRequest\x1a\x31.assessorflow.knowledge.v1.GetChunksByIdsResponseB\x02P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'assessorflow.knowledge.v1.knowledge_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001'
  _globals['_CHUNK_METADATAENTRY']._loaded_options = None
  _globals['_CHUNK_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_CHUNK']._serialized_start=73
  _globals['_CHUNK']._serialized_end=287
  _globals['_CHUNK_METADATAENTRY']._serialized_start=240
  _globals['_CHUNK_METADATAENTRY']._serialized_end=287
  _globals['_TOPIC']._serialized_start=289
  _globals['_TOPIC']._serialized_end=381
  _globals['_GETTOPICSREQUEST']._serialized_start=383
  _globals['_GETTOPICSREQUEST']._serialized_end=422
  _globals['_GETTOPICSRESPONSE']._serialized_start=424
  _globals['_GETTOPICSRESPONSE']._serialized_end=514
  _globals['_SIMILARITYSEARCHREQUEST']._serialized_start=516
  _globals['_SIMILARITYSEARCHREQUEST']._serialized_end=632
  _globals['_SIMILARITYSEARCHRESPONSE']._serialized_start=634
  _globals['_SIMILARITYSEARCHRESPONSE']._serialized_end=731
  _globals['_GETCHUNKSBYIDSREQUEST']._serialized_start=733
  _globals['_GETCHUNKSBYIDSREQUEST']._serialized_end=775
  _globals['_GETCHUNKSBYIDSRESPONSE']._serialized_start=777
  _globals['_GETCHUNKSBYIDSRESPONSE']._serialized_end=851
  _globals['_KNOWLEDGESERVICE']._serialized_start=854
  _globals['_KNOWLEDGESERVICE']._serialized_end=1220
# @@protoc_insertion_point(module_scope)
